### PR TITLE
Demo

### PR DESCRIPTION
**Pull request by lrljoe**
Several tweaks:
- Add Countries model, table
- Add country_id to Links table
- Add seeder for Countries using a flat SQL file
- Add seed for Links to set a valid country_id
- Set Countries array in Table to be generated by Country model
- Set filter to limit based on country_id

If this was a real world scenario, you could run
UPDATE links set country_id = (select id from countries where name = cuntry);
To update the links.

### CODE REVIEW

**Comment by lrljoe** [comment]
I've also added in an example of how you can use a Flag Icon in a dropdown by separating out the countries properly, and leveraging flag-icons JS package, e.g.
image

**Comment by BenOussama180** [comment]
@lrljoe thanks alot for the help ! btw i dont see the flags in the smart select for some reason i havent changed anything  from your code its a lil bit wierd!
the DateRangeFilter is not working, no errors are **NOT** throwns but when i click it doesnt display the flatpicker date picker

**Comment by lrljoe** [comment]
Did you run the migrations and db seed?

**Comment by BenOussama180** [comment]
yes i did : 
php artisan migrate:fresh --seed
npm install
composer install
php artisan serve
npm run dev

**Comment by lrljoe** [comment]
In your database, do you have a countries table, and does it have id,code,name?
If you do
npm update
npm run build

What do you get?
What version of npm/nodejs do you have in your environment?

After running "npm run build" you should have a load of flag svg files in your public/build/assets folder, are they present?

**Comment by lrljoe** [comment]
For my instance of your demo:
http://benoussama.lowerrocklabs.com/dashboard
username: 123@test
password: Password123

**Comment by lrljoe** [comment]
Can you paste the output of:
npm -v
node -v
npm ls
All run in your directory

**Comment by BenOussama180** [comment]
NB : i forgot to add this to my  app.js 
`import "flatpickr/dist/flatpickr.min.css";
`
now the datepicker works ! 
the smart select works also but the flags arent showing, itried to show it in my dashboard as a normal span it does not show i tihnk its related to my flagicons package : 
image

**Comment by BenOussama180** [comment]
and the overflow is still an issue when theres no data on the table 
image
but as you said its table related

**Comment by BenOussama180** [comment]
the flagicons package works 
image
i think its something with tthe html on my smartselect, yes i have seen the demo you mentioned it works there for somereason it doesnt on my local weird!

```php
if (empty($this->arrayOfCountries)) {
            $this->arrayOfCountries = Country::select('id', 'name', 'code')
                ->orderBy('name')
                ->get()
                ->map(function ($country) {
                    $countryValue['id'] = $country->id;
                    $countryValue['name'] = $country->name;
                    $countryValue['htmlName'] = "<span><span class='fi fi-" . strtolower($country->code) . "'></span>" . $country->name . "</span>";

                    return $countryValue;
                })
                ->keyBy('id')
                ->toArray();
        }
SmartSelectFilter::make('Country', 'cuntry')
                ->config(['displayHtmlName' => true,])

                ->options(
                    $this->arrayOfCountries
                )
                ->filter(function (Builder $builder, array $values) {
                    $builder->whereIn('country_id', $values);
                }),
```
```php
'smartSelect' => [
        'optionsMethod' => 'complex',  // Should be set to either standard or lookup
        'popoverMethod' => 'standard',  // Should be set to either standard or lookup.
        'iconStyling' => [
            'add' => [
                'classes' => '',        // Base classes for the "add" icon
                'defaults' => true,     // Determines whether to merge (true) or replace (false) the default class (inline-block)
                'svgEnabled' => true,  // Enable or Disable the use of the default SVG icon
                'svgFill' => '#000000', // Fill for the SVG Icon
                'svgSize' => '1.5em',   // Size for the SVG Icon
            ],
            'delete' => [
                'classes' => '',        // Base classes for the "delete" icon
                'defaults' => true,     // Determines whether to merge (true) or replace (false) the default class (inline-block)
                'svgEnabled' => true,   // Enable or Disable the use of the default SVG icon
                'svgFill' => '#000000', // Fill for the SVG Icon
                'svgSize' => '1.5em',   // Size for the SVG Icon
            ],
        ],
        'listStyling' => [
            'classes' => '',            // Classes for the list items
            'defaults' => true,         // Determines whether to merge (true) or replace (false) the default classes
        ],
        'closeAfterAdd' => true,        // Close the smartSelect after adding an item
        'closeAfterRemove' => true,     // Close the smartSelect after removing an item
    ],
```

**Comment by lrljoe** [comment]
Two quick things.

Make sure your setup for the arrayOfCountries is in your configure method.

If you devtools on an item in the smartselect, what do you see?

**Comment by BenOussama180** [comment]
```html
<li class="px-2 py-1 hover:bg-blue-500 dark:hover:bg-gray-400 dark:bg-gray-800" :class="{ 'dark:bg-gray-800': (index % 2) }">
                                <template x-if="selectedItems.indexOf(filteredItem.id.toString()) > -1">
                                    <a class="cursor-pointer  inline-block w-full" x-on:click="removeSelectedItem(filteredItem.id.toString())">
                    <svg class="inline-block " fill="currentColor" width="1.5em" height="1.5em" viewBox="0 0 297 297" xml:space="preserve" xmlns="http://www.w3.org/2000/svg">
        <path d="m150.33 203.76c0-32.35 26.317-58.667 58.667-58.667 6.527 0 12.8 1.087 18.669 3.063l4.882-58.587h-185.39l14.518 174.21c1.552 18.627 17.41 33.219 36.103 33.219h84.147c18.692 0 34.551-14.592 36.103-33.219l0.173-2.081c-3.001 0.475-6.075 0.729-9.207 0.729-32.349 0-58.667-26.317-58.667-58.667z"></path>
        <path d="m209 158.71c-24.839 0-45.048 20.209-45.048 45.048s20.209 45.048 45.048 45.048 45.048-20.209 45.048-45.048-20.209-45.048-45.048-45.048zm22.101 57.518c2.659 2.66 2.659 6.971 0 9.631-1.33 1.329-3.073 1.994-4.816 1.994-1.742 0-3.486-0.665-4.816-1.994l-12.469-12.47-12.47 12.47c-1.33 1.329-3.073 1.994-4.816 1.994-1.742 0-3.486-0.665-4.816-1.994-2.659-2.66-2.659-6.971 0-9.631l12.47-12.47-12.47-12.47c-2.659-2.66-2.659-6.971 0-9.631 2.66-2.658 6.971-2.658 9.631 0l12.47 12.47 12.47-12.47c2.661-2.658 6.972-2.658 9.632 0 2.659 2.66 2.659 6.971 0 9.631l-12.47 12.47 12.47 12.47z"></path>
        <path d="m112.1 26.102c0-6.883 5.6-12.483 12.483-12.483h30.556c6.884 0 12.484 5.6 12.484 12.483v8.507h13.619v-8.507c1e-3 -14.392-11.709-26.102-26.102-26.102h-30.556c-14.392 0-26.102 11.71-26.102 26.102v8.507h13.618v-8.507z"></path>
        <path d="m236.76 63.643c0-8.5-6.915-15.415-15.415-15.415h-162.98c-8.5 0-15.415 6.915-15.415 15.415v12.31h193.81v-12.31z"></path>
    </svg>
                <span class="smartSelect-NameDisplay-Wrapper pl-1">
            <template x-if="displayIdEnabled">
                <span class="smartSelect-NameDisplay-ID">
                    (<span x-text="filteredItem.id"></span>)
                </span>
            </template>
            <span class="smartSelect-NameDisplay-Name" x-text="filteredItem.name"></span>
        </span>
    </a>
                                </template>
                                <template x-if="selectedItems.indexOf(filteredItem.id.toString()) < 0">
                                    <a class="cursor-pointer inline-block w-full" x-on:click="addSelectedItem(filteredItem.id.toString())">
                    <svg class="inline-block " width="1.5em" height="1.5em" version="1.1" viewBox="0 0 297 297" xml:space="preserve" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path d="m182.41 170.37c-11.317 0-22.632 4.307-31.248 12.922-17.23 17.231-17.23 45.265 0 62.496 17.232 17.23 45.264 17.23 62.496 0 17.23-17.231 17.23-45.265 0-62.496-8.615-8.614-19.931-12.922-31.248-12.922zm23.981 50.851h-17.301v17.301c0 3.689-2.991 6.68-6.68 6.68s-6.68-2.991-6.68-6.68v-17.301h-17.301c-3.689 0-6.68-2.991-6.68-6.68s2.991-6.68 6.68-6.68h17.301v-17.301c0-3.689 2.991-6.68 6.68-6.68s6.68 2.991 6.68 6.68v17.301h17.301c3.689 0 6.68 2.991 6.68 6.68s-2.99 6.68-6.68 6.68z"></path>
        <path d="m227.29 92.758c-2.303 0-4.62 0.117-6.931 0.349-8.746-32.121-38.001-54.816-71.858-54.816s-63.112 22.695-71.858 54.817c-2.311-0.232-4.628-0.349-6.931-0.349-38.439-1e-3 -69.711 31.271-69.711 69.71s31.272 69.712 69.711 69.712h57.948c-6.372-19.889-1.696-42.58 14.06-58.337 22.44-22.438 58.949-22.438 81.39 0 15.556 15.557 20.318 37.875 14.304 57.58 33.655-4.918 59.587-33.956 59.587-68.955 0-38.439-31.272-69.711-69.711-69.711z"></path>
    </svg>
                <span class="smartSelect-NameDisplay-Wrapper pl-1">
            <template x-if="displayIdEnabled">
                <span class="smartSelect-NameDisplay-ID">
                    (<span x-text="filteredItem.id"></span>)
                </span>
            </template>
            <span class="smartSelect-NameDisplay-Name" x-text="filteredItem.name"></span>
        </span>
    </a>
                                </template><a class="cursor-pointer inline-block w-full" x-on:click="addSelectedItem(filteredItem.id.toString())">
                    <svg class="inline-block " width="1.5em" height="1.5em" version="1.1" viewBox="0 0 297 297" xml:space="preserve" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path d="m182.41 170.37c-11.317 0-22.632 4.307-31.248 12.922-17.23 17.231-17.23 45.265 0 62.496 17.232 17.23 45.264 17.23 62.496 0 17.23-17.231 17.23-45.265 0-62.496-8.615-8.614-19.931-12.922-31.248-12.922zm23.981 50.851h-17.301v17.301c0 3.689-2.991 6.68-6.68 6.68s-6.68-2.991-6.68-6.68v-17.301h-17.301c-3.689 0-6.68-2.991-6.68-6.68s2.991-6.68 6.68-6.68h17.301v-17.301c0-3.689 2.991-6.68 6.68-6.68s6.68 2.991 6.68 6.68v17.301h17.301c3.689 0 6.68 2.991 6.68 6.68s-2.99 6.68-6.68 6.68z"></path>
        <path d="m227.29 92.758c-2.303 0-4.62 0.117-6.931 0.349-8.746-32.121-38.001-54.816-71.858-54.816s-63.112 22.695-71.858 54.817c-2.311-0.232-4.628-0.349-6.931-0.349-38.439-1e-3 -69.711 31.271-69.711 69.71s31.272 69.712 69.711 69.712h57.948c-6.372-19.889-1.696-42.58 14.06-58.337 22.44-22.438 58.949-22.438 81.39 0 15.556 15.557 20.318 37.875 14.304 57.58 33.655-4.918 59.587-33.956 59.587-68.955 0-38.439-31.272-69.711-69.711-69.711z"></path>
    </svg>
                <span class="smartSelect-NameDisplay-Wrapper pl-1">
            <template x-if="displayIdEnabled">
                <span class="smartSelect-NameDisplay-ID">
                    (<span x-text="filteredItem.id"></span>)
                </span>
            </template>
            <span class="smartSelect-NameDisplay-Name" x-text="filteredItem.name">American Samoa</span>
        </span>
    </a>
                            </li>
```

**Comment by lrljoe** [comment]
Display issue:
In your dashboard.blade.php you've wrapped the <livewire:link-table /> with "overflow-hidden", you'll need to change that to "overflow-visible", and the filter will display properly when there's no rows.

For the flags, I've just realised that I forgot to publish a new version, 1.0.9 is released which has the extra functionality to enable the HtmlName.

**Comment by BenOussama180** [comment]
i have your latest version now ! 
"lowerrocklabs/laravel-livewire-tables-advanced-filters": "^1.0.9",
but still no flags, which is weird, i see in vendor views that yoou have an @if(displayNameHtml) and i pass it as true from the config & still nothing shows up which is weird, i pushed the latest code into my repo

**Comment by lrljoe** [comment]
Jeez I must need some sleep.  In your Table Component, change
                ->config(['displayHtmlName' => false])
to
                ->config(['displayHtmlName' => true])

As to display an HtmlName, that has to be set to true (which I really should have spotted)

It immediately started working for me when I did that.

**Comment by BenOussama180** [comment]
godamn you have a tiger eye, everything works well now ! thanks alot man for this package ! i will use it in my production app for my work !  get some rest king

**Comment by lrljoe** [comment]
No problem, there's a few more bits and pieces still in the works, so do expect fairly regular updates over the next few weeks, and some decent UX improvements all-round, as I was mostly focused on just getting it all working!

**Comment by BenOussama180** [comment]
one more qst non package related but i've been stuck oon it foor a while now : 
image
u got any idea how to set the min & max values with Link::max('as') , but having it directly there makes ALOT of queries to the database , how can i put it inside an additional select or anything

**Comment by lrljoe** [comment]
You can retrieve the maximum as value in the DB by:
```php
$maxLink = \Illuminate\Support\Facades\DB::select("select max(`as`) as 'maxAS' from links")[0]->maxAS;
```
You can then pass that into the min/max values as you like.  That should just perform a single query.

Pass it into minRange/maxRange if you're looking to adjust the range of the selection, you can remove the options if you choose, and it'll default to the minRange/maxRange values.
```php                ->options(
                    [
                        'min' => 100,
                        'max' => 1000
                    ]
                )
```
You can always set it as a protected variable in configure, and pass it into the filter to avoid the default Rappasoft behaviour of iterating through the filters a couple of times.

**Pull request merged**
