### PR TITLE
Filtering on dates

### PR DESCRIPTION
**Pull request by lrljoe**
See this example for filtering on dates etc

### CODE REVIEW

**Comment by BenOussama180** [comment]
hello @lrljoe , i have a question , how would you achieve a footer that would calculate the total for this column for example 
```php
Column::make("Total - Status 5")
                ->label(function ($row, $column) {
                    return $row->orders->where('status', 5)->sum('price') ?? '0';
                }),
```
what would you put in the  
```php
 ->footer()
```
 method ?

**Comment by lrljoe** [comment]
I'm assuming you want the sum of the displayed items?  I.e. if there's a filter, then sum the filtered items, if no filter then sum the unfiltered items?

**Comment by lrljoe** [comment]
Not in front of my computer at the mo, but the following should work
```php
            Column::make("Total - Status 3 or 4")
                ->label(function ($row, $column) {
                    return $row->orders->whereIn('status', ['3', '4'])->sum('price') ?? '0';
                })->footer(function($rows) {
                    return 'Subtotal: ' . $rows->sum(function ($row) {
                        return $row->orders->whereIn('status', ['3', '4'])->sum('price');
                    });
                }),
```

**Comment by BenOussama180** [comment]
cant imagine my life with package without you man @lrljoe , thanks alot for the help , your code works like magic!
never knew the ->sum() can take a callback until now! thanks alot man

**Comment by BenOussama180** [comment]
cant imagine my life with package without you man @lrljoe , thanks alot for the help , your code works like magic!
never knew the ->sum() can take a callback until now! thanks alot man

**Comment by lrljoe** [comment]
It's a genuine pleasure to help you!  I'm glad you're finding it helpful

**Comment by BenOussama180** [comment]
hey again @lrljoe , this PR will probably be the most commented PR in history of github LOL , 
i have  question regarding the builder method 
so i want to display all invoices by user , im using laravel cashier so im getting stripe invices usiing $user->invoices(), the prblem is that invoices() returns a collection and not a builder
image

and when i change the return type to Collection doesnt work also : 
```php
public function builder(): Collection
    {
        return User::find($this->userId)->invoices();
    }
```
image

**Comment by lrljoe** [comment]
Apologies, I have filters so I don't see comments on closed PRs until I skim through my email!

Are you still having an issue with this?

**Comment by BenOussama180** [comment]
> Apologies, I have filters so I don't see comments on closed PRs until I skim through my email!
> 
> Are you still having an issue with this?

yes i still have it!

**Comment by lrljoe** [comment]
It's not a particularly straight forward one I'm afraid, as the data table component is purely designed to work with effectively builder instances!  I've stuck an example down below, but what I would probably do in this instance is the following:

1. Create a basic model for the invoices with a database table (e.g. StripeInvoices)
2. Enable the Stripe webhooks for Invoices
3. Parse the basic data into a model (i.e. the stripe reference, perhaps the invoice title, dates etc) when it is sent from Stripe to the webhook.

In terms of webhooks you've got these (at least!)
- Invoice created
- Invoice updated
- Invoice payment succeeded
- Invoice payment failed
- Invoice paid (out of bounds)

So you could just set up your webhooks to populate a basic "StripeInvoices" model with the core information and use that relation instead to display the basic information.

It'll also:
- Be much faster/more efficient when you want to work with the data elsewhere
- If the worst happens and Stripe goes offline for a day or two, you've still got the basic data to hand
- Reduce the risk of "man-in-the-middle", 
- Improve the UX as they haven't got to wait for the 

Then you can just call the data as normal, and use the invoices() collection for outputting anything additional that Stripe don't pass back, but I'd really recommend storing most of the straight-forward items locally where you can filter/search on it in a more straight forward fashion!

If that all feels like too much work, then you could just override the render() method, but things **WILL NOT** work as you'd expect!

```php
    /**
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function render()
    {
        $this->setupColumnSelect(); // This is required to display the columns
       // $this->setupPagination(); // You cannot use this pagination method, as it relies on the builder instance
        $this->setupSecondaryHeader(); // This probably won't work either
        $this->setupFooter(); // This probably won't work either
        // $this->setupReordering(); // You cannot use this re-ordering method, as it relies on the builder instance

        return view('livewire-tables::datatable')
            ->with([
                'columns' => $this->getColumns(),
                'rows' => Auth::user()->invoices()->paginate(), // You'll have to load() any additional relations you need for your columns.
                'customView' => $this->customView(),
            ]);
    }
```

**Comment by BenOussama180** [comment]
hmmm,  thanks for the clear answer, i think creating a proper invoice model would be the best option to do ! i will work on that !

**Comment by lrljoe** [comment]
Probably easiest to extend the cashier invoice model so that you have all the functionality  like tax calculation etc.


That way you'll just need to do the following

Create a model which extends cashier invoice

create a migration with the fields you need.

Set your model to use that dB table

When the webhook comes in, instantiate your model from the instance sent via the webhook, and then use the save method to get it into the database

Should be very straightforward, someone else will have definitely done it already, so might be worth having a search on GitHub to see if they have published anything.




Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by BenOussama180** [comment]
hmm this actually sounds very smart to do i will see how to achieve this thank u so much.

where should i search exactly for such specific thing on github ?

**Pull request merged**
